### ISSUE TITLE
Galaxy Watch 4 - Only three entries listed 

### ISSUE THREAD

**Issue by MoritzWeber0** [DaneChainS/weaOTP-doc#2]
Hi, the app works perfectly on my Galaxy Watch 4 (running wearOS 3). Is there are way to see more then three entries already? Right now it is limited to three entries. 

Thank you for the answer in advance!

**Comment by DaneChainS** [comment]
Hi, nice to see a second user/tester. Which GW4 size are you using, 40 or 44mm? Depending on that the displayed elements might be a little off and could need tuning.
Until now the only screen sizes tested and adjusted was for a Huawei Watch and a GW4 44mm.
In the loading screen (press back when on the normal codes screen) you can then scroll down, select "unlock beta" and let me know the id shown. I will give you a code to unlock my testing mode which should get rid of all limitations at your own risk. Just let me know any problems you face, I will try to fix them.
(you can also consider testing poins I listed [here (issue on andOTP project)](https://github.com/andOTP/andOTP/issues/68#issuecomment-965606482) 

One more question (since my other user/tester is not using it): are you using the bundled phone companion (W)andOTP app with bluetooth sync or the backup file loading mode on your watch standalone?

**Comment by MoritzWeber0** [comment]
Hi, thanks for the reply. I am now using another app, but I can still give a short feedback:
- I'm using the 40mm version of the GW4. 
- I loaded the encrypted backup via the Galaxy Wearable app (as mp3 file). It worked perfectly! Decrypting the backup file took about 15 seconds (my main phone is the OnePlus Nord 1). That's not a problem either, because the decryption only takes place once.
- The complete text was visible, in general everything was in the right place. Usability was perfect. 
- I used the app for a day but didn't notice any increase in battery consumption.

I hope this is of some help! Do you plan to publish the source code to Github?

**Comment by DaneChainS** [comment]
Thanks for the answers, sure they help, as it has not been tested on that screen size yet. 

Yes, the initial plan was to publish/ integrate all this in andOTP as the issue there is open since some years already. Before publishing I want to do some cleanup/ polishing and have it tested at least a bit. However at the moment I don't really see that additional work justified due to the lack of interest/demand. (You are the 2nd person in 3 month...)  
Which is fine as it is primarily a personal use tool for me and I would have spent that work until here anyway. But not more currently. Of course I will do adjustments for new screens when the 3rd or 4th user needs them :-)

**Comment by filviu** [comment]
Sorry to hijack, but I wanted to comment with regards to the lack of interest:

- It was pretty hard to find this effort: I just got a Samsung Watch4 and at first search all I found was that andOTP doesn't support wearOS but AuthenticatorPro (also open source) already has similar features and a working watch app that syncs with the phone app. Almost by mistake I found the Github Issue that mentions this project.
- It's a sensible area, I'm sure few people want to experiment with their security keys - I plan to start testing weaOTP soon but need to create a dummy list of accounts - until this is open source and merged into the main project I won't trust it with my real credentials.
- I bet there will be a rise in interest - the Samsung Galaxy watch is arguably one of the more common smartwatches for android users and they just switched to WearOS. The more people upgrade to Watch4 (or 5 when released) from the Tizen watches the more people will need WearOS apps.

**Comment by DaneChainS** [comment]
No worries, but to not spam the OP with notifications, I will close this issue, and in case you you do some beta testing, just open a new one.
But you are right, never trust any app on the internet... That's one reason why I made my own. ;-)
The second one was: I did not know/find AuthenticatorPro, as I already used andOTP.
I still have not checked it out on my devices, but I'm sure it is good too. Please consider supporting the great work of these guys.
Maybe I test it later, but currently the functionality of my own app is enough for me. And I really like my tile implementation and ease of access for daily use.
